apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-ventas-deployment
  namespace: examen
spec:
  replicas: 2
  selector:
    matchLabels:
      app: back-ventas
  template:
    metadata:
      labels:
        app: back-ventas
    spec:
      containers:
      - name: back-ventas
        image: 680891292484.dkr.ecr.us-east-1.amazonaws.com/examen-back-ventas:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://db-service:3306/examen_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "admin123"
