apiVersion: apps/v1
kind: Deployment
metadata:
  # Se inicializa el despliegue para el microservicio de ventas
  name: back-ventas-deployment
  namespace: examen
spec:
  replicas: 2
  selector:
    matchLabels:
      app: back-ventas
  template:
    metadata:
      labels:
        app: back-ventas
    spec:
      containers:
        - name: back-ventas
          # Se vincula la imagen almacenada en ECR para el backend de ventas
          image: 680891292484.dkr.ecr.us-east-1.amazonaws.com/examen-back-ventas:latest
          imagePullPolicy: Always
          ports:
            # Se expone el puerto estándar del contenedor Spring Boot
            - containerPort: 8080
          # Se establece la asignación de recursos mínimos y máximos para posibilitar el cálculo de porcentajes del HPA
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"