apiVersion: apps/v1
kind: Deployment
metadata:
  # Se inicializa el despliegue para el microservicio de ventas
  name: back-ventas-deployment
  namespace: examen
spec:
  replicas: 2
  selector:
    matchLabels:
      app: back-ventas
  template:
    metadata:
      labels:
        app: back-ventas
    spec:
      containers:
      - name: back-ventas
        image: 680891292484.dkr.ecr.us-east-1.amazonaws.com/examen-back-ventas:latest
        ports:
        - containerPort: 8080
        # TUS LÍMITES ESTÁN PERFECTOS, MANTENLOS:
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
        # AÑADE ESTE BLOQUE ENV:
        env:
        - name: SPRING_AUTOCONFIGURE_EXCLUDE
          value: "org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration"
