apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  # Se configura el escalado dinámico para absorber la carga en el servicio de ventas
  name: back-ventas-hpa
  namespace: examen
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: back-ventas-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50